package cli

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"

	"github.com/jzbz/brb/internal/agecrypt"
	"github.com/jzbz/brb/internal/config"
	"github.com/jzbz/brb/internal/restore"
	"github.com/jzbz/brb/internal/ui"
)

// rescueIdentityName is the file the rescue identity lives in, beside the
// recipients file. The name is not configurable: it is the last of the
// candidates restore's findIdentity tries, and brb.sh's find_identity tries the
// same one in the same place. A rescue key under any other name is a key the
// restore side will not find on the day it is needed.
const rescueIdentityName = "rescue-identity.txt.age"

// initKey generates an age keypair, writes the secret identity beside the
// recipients file with mode 0400, and appends the public key to the recipients
// file. Unlike brb.sh it needs no age-keygen binary — the key is generated by
// the age library brb already links.
//
// An existing identity file is never overwritten: the identity is the only
// thing that can decrypt a set, so silently replacing one would orphan every
// disc already burned with it.
//
// With rescue set, a second keypair is minted as well and its public key
// appended too, so every disc from then on is encrypted to both; see
// [initRescueKey]. That half is additive by design — it must work on an archive
// that already exists, so an identity file that is already there is left
// exactly as it is rather than being a refusal.
func initKey(cfg *config.Config, p *ui.Printer, rescue bool) error {
	if cfg.AgeRecipientsFile == "" {
		return errors.New("init-key: AGE_RECIPIENTS_FILE is empty")
	}
	// Resolve the identity path the same way restore does: an explicitly
	// configured AGE_IDENTITY wins, otherwise it sits beside the recipients
	// file. Writing to the default while restore reads AGE_IDENTITY would put
	// the only key that can decrypt the set somewhere restore never looks.
	keyFile := cfg.AgeIdentity
	if keyFile == "" {
		keyFile = filepath.Join(filepath.Dir(cfg.AgeRecipientsFile), "identity.txt")
	}
	keyDir := filepath.Dir(keyFile)

	if err := os.MkdirAll(keyDir, 0o700); err != nil {
		return fmt.Errorf("init-key: creating %s: %w", keyDir, err)
	}
	if err := os.Chmod(keyDir, 0o700); err != nil {
		return fmt.Errorf("init-key: securing %s: %w", keyDir, err)
	}
	// The recipients file need not live beside the identity once AGE_IDENTITY
	// points elsewhere, so make sure its directory exists before appending.
	if recDir := filepath.Dir(cfg.AgeRecipientsFile); recDir != keyDir {
		if err := os.MkdirAll(recDir, 0o700); err != nil {
			return fmt.Errorf("init-key: creating %s: %w", recDir, err)
		}
	}
	exists := false
	if _, err := os.Lstat(keyFile); err == nil {
		exists = true
	} else if !errors.Is(err, fs.ErrNotExist) {
		return fmt.Errorf("init-key: %s: %w", keyFile, err)
	}
	if exists && !rescue {
		return fmt.Errorf("init-key: %s already exists — refusing to overwrite it", keyFile)
	}
	if exists {
		p.OK("identity %s is already there — leaving it untouched", keyFile)
		p.Step("adding the rescue key only; the existing key still decrypts every disc already burned")
	} else if err := initPrimaryKey(cfg, p, keyFile, rescue); err != nil {
		return err
	}
	if rescue {
		if err := initRescueKey(cfg, p); err != nil {
			return err
		}
	}
	p.Step("check it with: brb doctor   (it proves this key decrypts what it encrypts)")
	return nil
}

// initPrimaryKey mints the machine's own keypair and records it. The advice
// that follows is the whole reason init-key prints anything at all: the key is
// worthless in a password manager nobody put it in.
func initPrimaryKey(cfg *config.Config, p *ui.Printer, keyFile string, rescue bool) error {
	id, err := agecrypt.GenerateIdentity()
	if err != nil {
		return fmt.Errorf("init-key: %w", err)
	}
	if err := agecrypt.WriteIdentityFile(keyFile, id); err != nil {
		return fmt.Errorf("init-key: %w", err)
	}
	pub := id.Recipient().String()
	if err := agecrypt.AppendRecipient(cfg.AgeRecipientsFile, pub); err != nil {
		// The identity is on disk but unusable for a backup without its public
		// key recorded; say exactly how to finish the job by hand.
		return fmt.Errorf("init-key: identity written to %s, but recording %s in %s failed: %w",
			keyFile, pub, cfg.AgeRecipientsFile, err)
	}

	p.OK("keypair generated")
	p.Raw("")
	p.Raw("  Secret identity : %s   (mode 0400)", keyFile)
	p.Raw("  Public key      : %s", pub)
	p.Raw("  Recipients file : %s", cfg.AgeRecipientsFile)
	p.Raw("")
	p.Warn("Losing the secret identity means losing every backup.")
	p.Raw("  Before you burn anything:")
	p.Raw("")
	p.Raw("    1. Put %s in your password manager.", keyFile)
	p.Raw("    2. Print it and store the paper elsewhere. It is one short line.")
	if !rescue {
		p.Raw("    3. Give yourself a second way in:")
		p.Raw("         brb init-key --rescue-key")
		p.Raw("       It adds a second recipient whose identity is passphrase-protected,")
		p.Raw("       so the set restores with either the key file or something you")
		p.Raw("       remember. It can be run later, on a set that already exists.")
	}
	p.Raw("")
	p.Raw("  Append more public keys to %s to make every image", cfg.AgeRecipientsFile)
	p.Raw("  decryptable by any of them.")
	p.Raw("")
	return nil
}

// initRescueKey mints a second keypair, stores its identity in an age container
// encrypted under a passphrase typed here, and appends its public key to the
// recipients file so every image from now on is encrypted to both.
//
// Why this shape, and not `age -p` over the images themselves: the discs stay
// encrypted to public keys, so the passphrase never guards the ciphertext a
// thief walks away with — only a small file they do not have. age also refuses
// to mix an scrypt stanza with recipient stanzas, so "my key or my passphrase"
// cannot be written into one file at all. What it can be written as is a second
// recipient, which is exactly this.
//
// The plaintext identity is never a file: it goes straight into the encrypted
// container. See [agecrypt.WriteEncryptedIdentityFile].
func initRescueKey(cfg *config.Config, p *ui.Printer) error {
	// Beside the recipients file, not beside AGE_IDENTITY: that is the one
	// place both readers look for it.
	out := filepath.Join(filepath.Dir(cfg.AgeRecipientsFile), rescueIdentityName)
	if _, err := os.Lstat(out); err == nil {
		return fmt.Errorf("init-key: %s already exists — refusing to overwrite it. "+
			"A rescue key you cannot open is indistinguishable from one you can, so replacing it "+
			"has to be deliberate: move it aside first", out)
	} else if !errors.Is(err, fs.ErrNotExist) {
		return fmt.Errorf("init-key: %s: %w", out, err)
	}
	// Refuse under --yes rather than prompting, exactly as the restore side
	// refuses to unlock an encrypted identity under it: --yes promises an
	// unattended run, and a run that stops to ask for a passphrase is not one.
	if p.AssumeYes() {
		return errors.New("init-key: --rescue-key has to ask for a passphrase on the terminal, " +
			"and --yes is in effect; there is nobody to type it — run 'brb init-key --rescue-key' without --yes")
	}

	p.Log("minting a rescue key")
	p.Step("its identity is stored encrypted under a passphrase you choose now.")
	p.Step("the passphrase is not recoverable and is not written anywhere:")
	p.Step("forgetting it makes %s so much noise.", rescueIdentityName)

	pass, err := askNewPassphrase()
	if err != nil {
		return err
	}

	id, err := agecrypt.GenerateIdentity()
	if err != nil {
		return fmt.Errorf("init-key: %w", err)
	}
	if err := agecrypt.WriteEncryptedIdentityFile(out, id, pass); err != nil {
		return fmt.Errorf("init-key: %w", err)
	}
	pub := id.Recipient().String()
	if err := agecrypt.AppendRecipient(cfg.AgeRecipientsFile, pub); err != nil {
		// Same reasoning as the primary key: the container is on disk but no
		// image will be encrypted to it until the public key is recorded, and
		// a rescue key nothing is encrypted to is worse than none at all.
		return fmt.Errorf("init-key: rescue identity written to %s, but recording %s in %s failed: %w",
			out, pub, cfg.AgeRecipientsFile, err)
	}

	p.OK("rescue key generated")
	p.Raw("")
	p.Raw("  Rescue identity : %s   (mode 0400, passphrase-protected)", out)
	p.Raw("  Public key      : %s", pub)
	p.Raw("  Recipients file : %s", cfg.AgeRecipientsFile)
	p.Raw("")
	p.Raw("  Discs built from now on are encrypted to both keys; discs already")
	p.Raw("  burned are not, and still need the key they were built with.")
	p.Raw("")
	p.Raw("  That file is inert without the passphrase: copy it to a USB stick, a")
	p.Raw("  cloud drive, a relative's machine. Restoring with it needs no flags —")
	p.Raw("  once the plain identity is gone, brb finds it and asks once.")
	p.Raw("")
	return nil
}

// askNewPassphrase reads the rescue passphrase twice on the terminal and
// returns it only if the two agree. It is the restore side's prompt, so a
// passphrase this accepts is one that prompt can later read back.
//
// The three ways it fails are three different sentences, because "no terminal"
// told to somebody sitting at a terminal is a wrong answer that costs an hour.
func askNewPassphrase() (string, error) {
	pass, err := restore.ReadPassphrase("choose a passphrase for the rescue key: ")
	if err != nil {
		return "", newPassphraseError(err)
	}
	again, err := restore.ReadPassphrase("type it again: ")
	if err != nil {
		return "", newPassphraseError(err)
	}
	if pass != again {
		return "", errors.New("init-key: the two passphrases do not match — nothing was written")
	}
	return pass, nil
}

// newPassphraseError turns a prompt failure into the sentence that fits it.
// Every branch fails closed: no rescue key is written by any of them.
func newPassphraseError(err error) error {
	switch {
	case errors.Is(err, restore.ErrEmptyPassphrase):
		return errors.New("init-key: the passphrase was empty — a passphrase cannot be empty, " +
			"and it is the only thing protecting the rescue key. Nothing was written")
	case errors.Is(err, restore.ErrNoTerminal):
		return fmt.Errorf("init-key: --rescue-key needs a terminal to ask for a passphrase on. "+
			"It is read from /dev/tty and never from a pipe, so this cannot be automated — "+
			"run it from an interactive shell: %w", err)
	default:
		return fmt.Errorf("init-key: the passphrase could not be read — nothing was written: %w", err)
	}
}
